### ISSUE TITLE
neutron-agent-l3 cannot be started and timedout due to neutron_l3_agent_monitor() checking wrong port

### ISSUE THREAD

**Issue by zhangxiaolins** [madkiss/openstack-resource-agents#14]
neutron_l3_agent connect to rabbitmq via 5672 not to neutron server via 9696.

**Comment by aspiers** [comment]
Hi there.  This project has now moved to OpenStack governance:

- https://launchpad.net/openstack-resource-agents
- https://git.openstack.org/cgit/openstack/openstack-resource-agents/
- https://review.openstack.org/#/admin/projects/openstack/openstack-resource-agents
- https://review.openstack.org/#/q/status:open+project:openstack/openstack-resource-agents,n,z

Please could you re-assess whether this is still an issue, and if so, [submit it to launchpad](https://bugs.launchpad.net/openstack-resource-agents/+filebug)?  Many thanks!

**Comment by aspiers** [comment]
Actually it seems this was already fixed by #18.
