### ISSUE TITLE
Fix "plugin config" parameter in neutron-server

### ISSUE THREAD

**Issue by vthapar** [madkiss/openstack-resource-agents#16]
Parameter name is defined as "plugin config" which causes issues when trying to set it to non default value. This should be changed to "plugin_config"

<parameter name="plugin config" unique="0" required="0">
<parameter name="plugin_config" unique="0" required="0">

**Comment by aspiers** [comment]
Hi there.  This project has now moved to OpenStack governance:

- https://launchpad.net/openstack-resource-agents
- https://git.openstack.org/cgit/openstack/openstack-resource-agents/
- https://review.openstack.org/#/admin/projects/openstack/openstack-resource-agents
- https://review.openstack.org/#/q/status:open+project:openstack/openstack-resource-agents,n,z

It looks like this is still an issue upstream, so I have resubmitted a bug:

- https://bugs.launchpad.net/openstack-resource-agents/+bug/1508399

I have also just emailed @luxflux asking if he is able to submit his fix for this (and other issues) to the new gerrit-hosted repository.  Let's continue any conversation in the new bug.  Thanks!
